### ISSUE TITLE
Create template UMM-G output to be filled with info

### ISSUE THREAD

**Issue by lisakaser** [nsidc/granule-metgen#43]
1 story point

acceptance criteria:
Visual inspection of UMM-G JSON format by Amy

**Comment by juliacollins** [comment]
@afitzgerrell I've created a pull request for template file review! https://github.com/nsidc/granule-metgen/pull/59 Let me know if you have file formatting suggestions or spy a typo amongst all the `{` and `[`.

**Comment by afitzgerrell** [comment]
The Checksum object group can be removed from the templates. This is another case where I missed editing the examples I added to the UMM-G guidelines to remove it. In our guidelines, it's not included as a recommended attribute since it's optional and potentially adds another place where something can go awry. _If, however, this is a subelement that would make generating CNM messages easier, I could add this in the UMM-G guidelines as a DAAC recommendation!!_   

E.g., from ummg_template.json
 ~"Checksum": {
          "Value": "$checksum",
          "Algorithm": "SHA256"~

To my eyes, everything else checks out in the base template as well as all the spatial and temporal ummg templates.

**Comment by juliacollins** [comment]
The checksum section has been removed, and the pull request merged into the `main` branch.

**Comment by lisakaser** [comment]
Approving and moving to done.
